<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PersonKeyword', 'doctrine');

/**
 * BasePersonKeyword
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $person_id
 * @property integer $keyword_id
 * @property Person $Person
 * @property Keyword $Keyword
 * 
 * @method integer       getPersonId()   Returns the current record's "person_id" value
 * @method integer       getKeywordId()  Returns the current record's "keyword_id" value
 * @method Person        getPerson()     Returns the current record's "Person" value
 * @method Keyword       getKeyword()    Returns the current record's "Keyword" value
 * @method PersonKeyword setPersonId()   Sets the current record's "person_id" value
 * @method PersonKeyword setKeywordId()  Sets the current record's "keyword_id" value
 * @method PersonKeyword setPerson()     Sets the current record's "Person" value
 * @method PersonKeyword setKeyword()    Sets the current record's "Keyword" value
 * 
 * @package    gwis
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePersonKeyword extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('person_keyword');
        $this->hasColumn('person_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('keyword_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Person', array(
             'local' => 'person_id',
             'foreign' => 'id'));

        $this->hasOne('Keyword', array(
             'local' => 'keyword_id',
             'foreign' => 'id'));
    }
}