<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Keywordtype', 'doctrine');

/**
 * BaseKeywordtype
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $card_min
 * @property integer $card_max
 * @property Doctrine_Collection $Keyword
 * 
 * @method integer             getId()       Returns the current record's "id" value
 * @method string              getName()     Returns the current record's "name" value
 * @method integer             getCardMin()  Returns the current record's "card_min" value
 * @method integer             getCardMax()  Returns the current record's "card_max" value
 * @method Doctrine_Collection getKeyword()  Returns the current record's "Keyword" collection
 * @method Keywordtype         setId()       Sets the current record's "id" value
 * @method Keywordtype         setName()     Sets the current record's "name" value
 * @method Keywordtype         setCardMin()  Sets the current record's "card_min" value
 * @method Keywordtype         setCardMax()  Sets the current record's "card_max" value
 * @method Keywordtype         setKeyword()  Sets the current record's "Keyword" collection
 * 
 * @package    gwis
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseKeywordtype extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('keywordtype');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('card_min', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('card_max', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Keyword', array(
             'local' => 'id',
             'foreign' => 'keywordtype_id'));
    }
}