<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Doctype', 'doctrine');

/**
 * BaseDoctype
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $num
 * @property integer $activityitem_id
 * @property string $name
 * @property Activityitem $Activityitem
 * @property Doctrine_Collection $DocDoctype
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method integer             getNum()             Returns the current record's "num" value
 * @method integer             getActivityitemId()  Returns the current record's "activityitem_id" value
 * @method string              getName()            Returns the current record's "name" value
 * @method Activityitem        getActivityitem()    Returns the current record's "Activityitem" value
 * @method Doctrine_Collection getDocDoctype()      Returns the current record's "DocDoctype" collection
 * @method Doctype             setId()              Sets the current record's "id" value
 * @method Doctype             setNum()             Sets the current record's "num" value
 * @method Doctype             setActivityitemId()  Sets the current record's "activityitem_id" value
 * @method Doctype             setName()            Sets the current record's "name" value
 * @method Doctype             setActivityitem()    Sets the current record's "Activityitem" value
 * @method Doctype             setDocDoctype()      Sets the current record's "DocDoctype" collection
 * 
 * @package    gwis
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDoctype extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('doctype');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('num', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('activityitem_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Activityitem', array(
             'local' => 'activityitem_id',
             'foreign' => 'id'));

        $this->hasMany('DocDoctype', array(
             'local' => 'id',
             'foreign' => 'doctype_id'));
    }
}