<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('EventPerson', 'doctrine');

/**
 * BaseEventPerson
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $event_id
 * @property integer $person_id
 * @property Event $Event
 * @property Person $Person
 * 
 * @method integer     getEventId()   Returns the current record's "event_id" value
 * @method integer     getPersonId()  Returns the current record's "person_id" value
 * @method Event       getEvent()     Returns the current record's "Event" value
 * @method Person      getPerson()    Returns the current record's "Person" value
 * @method EventPerson setEventId()   Sets the current record's "event_id" value
 * @method EventPerson setPersonId()  Sets the current record's "person_id" value
 * @method EventPerson setEvent()     Sets the current record's "Event" value
 * @method EventPerson setPerson()    Sets the current record's "Person" value
 * 
 * @package    gwis
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEventPerson extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('event_person');
        $this->hasColumn('event_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('person_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Event', array(
             'local' => 'event_id',
             'foreign' => 'id'));

        $this->hasOne('Person', array(
             'local' => 'person_id',
             'foreign' => 'id'));
    }
}