<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('N2dwg', 'doctrine');

/**
 * BaseN2dwg
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $num
 * @property string $name
 * @property string $description
 * @property Doctrine_Collection $N2dwgSciencecase
 * @property Doctrine_Collection $Person
 * @property Doctrine_Collection $PersonN2dwg
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method string              getNum()              Returns the current record's "num" value
 * @method string              getName()             Returns the current record's "name" value
 * @method string              getDescription()      Returns the current record's "description" value
 * @method Doctrine_Collection getN2dwgSciencecase() Returns the current record's "N2dwgSciencecase" collection
 * @method Doctrine_Collection getPerson()           Returns the current record's "Person" collection
 * @method Doctrine_Collection getPersonN2dwg()      Returns the current record's "PersonN2dwg" collection
 * @method N2dwg               setId()               Sets the current record's "id" value
 * @method N2dwg               setNum()              Sets the current record's "num" value
 * @method N2dwg               setName()             Sets the current record's "name" value
 * @method N2dwg               setDescription()      Sets the current record's "description" value
 * @method N2dwg               setN2dwgSciencecase() Sets the current record's "N2dwgSciencecase" collection
 * @method N2dwg               setPerson()           Sets the current record's "Person" collection
 * @method N2dwg               setPersonN2dwg()      Sets the current record's "PersonN2dwg" collection
 * 
 * @package    gwis
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseN2dwg extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('n2dwg');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('num', 'string', 3, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 3,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('N2dwgSciencecase', array(
             'local' => 'id',
             'foreign' => 'n2dwg_id'));

        $this->hasMany('Person', array(
             'local' => 'id',
             'foreign' => 'n2dwg_id'));

        $this->hasMany('PersonN2dwg', array(
             'local' => 'id',
             'foreign' => 'n2dwg_id'));
    }
}