<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Expertise', 'doctrine');

/**
 * BaseExpertise
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $PersonExpertise
 * @property Doctrine_Collection $ResourceExpertise
 * 
 * @method integer             getId()                Returns the current record's "id" value
 * @method string              getName()              Returns the current record's "name" value
 * @method Doctrine_Collection getPersonExpertise()   Returns the current record's "PersonExpertise" collection
 * @method Doctrine_Collection getResourceExpertise() Returns the current record's "ResourceExpertise" collection
 * @method Expertise           setId()                Sets the current record's "id" value
 * @method Expertise           setName()              Sets the current record's "name" value
 * @method Expertise           setPersonExpertise()   Sets the current record's "PersonExpertise" collection
 * @method Expertise           setResourceExpertise() Sets the current record's "ResourceExpertise" collection
 * 
 * @package    gwis
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseExpertise extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('expertise');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 40, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 40,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('PersonExpertise', array(
             'local' => 'id',
             'foreign' => 'expertise_id'));

        $this->hasMany('ResourceExpertise', array(
             'local' => 'id',
             'foreign' => 'expertise_id'));
    }
}