<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DocDoctype', 'doctrine');

/**
 * BaseDocDoctype
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $doc_id
 * @property integer $doctype_id
 * @property Doc $Doc
 * @property Doctype $Doctype
 * 
 * @method integer    getDocId()      Returns the current record's "doc_id" value
 * @method integer    getDoctypeId()  Returns the current record's "doctype_id" value
 * @method Doc        getDoc()        Returns the current record's "Doc" value
 * @method Doctype    getDoctype()    Returns the current record's "Doctype" value
 * @method DocDoctype setDocId()      Sets the current record's "doc_id" value
 * @method DocDoctype setDoctypeId()  Sets the current record's "doctype_id" value
 * @method DocDoctype setDoc()        Sets the current record's "Doc" value
 * @method DocDoctype setDoctype()    Sets the current record's "Doctype" value
 * 
 * @package    gwis
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDocDoctype extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('doc_doctype');
        $this->hasColumn('doc_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('doctype_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Doc', array(
             'local' => 'doc_id',
             'foreign' => 'id'));

        $this->hasOne('Doctype', array(
             'local' => 'doctype_id',
             'foreign' => 'id'));
    }
}