<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Resource', 'doctrine');

/**
 * BaseResource
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $node_id
 * @property integer $resourcetype_id
 * @property integer $person_id
 * @property integer $person_updater_id
 * @property integer $person_responsible_id
 * @property integer $person_contact_id
 * @property integer $institute_id
 * @property integer $resource_repository_id
 * @property string $name
 * @property string $url
 * @property boolean $is_restricted
 * @property string $access_comment
 * @property string $brief
 * @property string $description
 * @property string $non_epn_location
 * @property string $howto
 * @property string $howto_url1
 * @property string $howto_url2
 * @property string $howto_url3
 * @property string $biblio_ref1
 * @property string $biblio_ref2
 * @property string $associated_url1
 * @property string $associated_url2
 * @property string $associated_url3
 * @property string $associated_url4
 * @property date $start_date
 * @property date $stop_date
 * @property boolean $is_english
 * @property enum $non_english_language
 * @property enum $language
 * @property string $responsible_name
 * @property string $responsible_email
 * @property string $contact_name
 * @property string $contact_email
 * @property integer $resourceformat_id
 * @property string $size
 * @property string $process_level
 * @property string $status
 * @property string $format_comment
 * @property boolean $is_copy
 * @property string $associated_url_comment
 * @property string $other_node_thematic
 * @property Institute $Institute
 * @property Node $Node
 * @property Person $Person
 * @property Person $Person_4
 * @property Person $Person_5
 * @property Person $Person_6
 * @property Node $Node_7
 * @property Resourceformat $Resourceformat
 * @property Resourcetype $Resourcetype
 * @property Doctrine_Collection $ResourceExpertise
 * @property Doctrine_Collection $ResourceKeyword
 * @property Doctrine_Collection $ResourceNode
 * @property Doctrine_Collection $ResourceSciencecase
 * 
 * @method integer             getId()                     Returns the current record's "id" value
 * @method integer             getNodeId()                 Returns the current record's "node_id" value
 * @method integer             getResourcetypeId()         Returns the current record's "resourcetype_id" value
 * @method integer             getPersonId()               Returns the current record's "person_id" value
 * @method integer             getPersonUpdaterId()        Returns the current record's "person_updater_id" value
 * @method integer             getPersonResponsibleId()    Returns the current record's "person_responsible_id" value
 * @method integer             getPersonContactId()        Returns the current record's "person_contact_id" value
 * @method integer             getInstituteId()            Returns the current record's "institute_id" value
 * @method integer             getResourceRepositoryId()   Returns the current record's "resource_repository_id" value
 * @method string              getName()                   Returns the current record's "name" value
 * @method string              getUrl()                    Returns the current record's "url" value
 * @method boolean             getIsRestricted()           Returns the current record's "is_restricted" value
 * @method string              getAccessComment()          Returns the current record's "access_comment" value
 * @method string              getBrief()                  Returns the current record's "brief" value
 * @method string              getDescription()            Returns the current record's "description" value
 * @method string              getNonEpnLocation()         Returns the current record's "non_epn_location" value
 * @method string              getHowto()                  Returns the current record's "howto" value
 * @method string              getHowtoUrl1()              Returns the current record's "howto_url1" value
 * @method string              getHowtoUrl2()              Returns the current record's "howto_url2" value
 * @method string              getHowtoUrl3()              Returns the current record's "howto_url3" value
 * @method string              getBiblioRef1()             Returns the current record's "biblio_ref1" value
 * @method string              getBiblioRef2()             Returns the current record's "biblio_ref2" value
 * @method string              getAssociatedUrl1()         Returns the current record's "associated_url1" value
 * @method string              getAssociatedUrl2()         Returns the current record's "associated_url2" value
 * @method string              getAssociatedUrl3()         Returns the current record's "associated_url3" value
 * @method string              getAssociatedUrl4()         Returns the current record's "associated_url4" value
 * @method date                getStartDate()              Returns the current record's "start_date" value
 * @method date                getStopDate()               Returns the current record's "stop_date" value
 * @method boolean             getIsEnglish()              Returns the current record's "is_english" value
 * @method enum                getNonEnglishLanguage()     Returns the current record's "non_english_language" value
 * @method enum                getLanguage()               Returns the current record's "language" value
 * @method string              getResponsibleName()        Returns the current record's "responsible_name" value
 * @method string              getResponsibleEmail()       Returns the current record's "responsible_email" value
 * @method string              getContactName()            Returns the current record's "contact_name" value
 * @method string              getContactEmail()           Returns the current record's "contact_email" value
 * @method integer             getResourceformatId()       Returns the current record's "resourceformat_id" value
 * @method string              getSize()                   Returns the current record's "size" value
 * @method string              getProcessLevel()           Returns the current record's "process_level" value
 * @method string              getStatus()                 Returns the current record's "status" value
 * @method string              getFormatComment()          Returns the current record's "format_comment" value
 * @method boolean             getIsCopy()                 Returns the current record's "is_copy" value
 * @method string              getAssociatedUrlComment()   Returns the current record's "associated_url_comment" value
 * @method string              getOtherNodeThematic()      Returns the current record's "other_node_thematic" value
 * @method Institute           getInstitute()              Returns the current record's "Institute" value
 * @method Node                getNode()                   Returns the current record's "Node" value
 * @method Person              getPerson()                 Returns the current record's "Person" value
 * @method Person              getPerson4()                Returns the current record's "Person_4" value
 * @method Person              getPerson5()                Returns the current record's "Person_5" value
 * @method Person              getPerson6()                Returns the current record's "Person_6" value
 * @method Node                getNode7()                  Returns the current record's "Node_7" value
 * @method Resourceformat      getResourceformat()         Returns the current record's "Resourceformat" value
 * @method Resourcetype        getResourcetype()           Returns the current record's "Resourcetype" value
 * @method Doctrine_Collection getResourceExpertise()      Returns the current record's "ResourceExpertise" collection
 * @method Doctrine_Collection getResourceKeyword()        Returns the current record's "ResourceKeyword" collection
 * @method Doctrine_Collection getResourceNode()           Returns the current record's "ResourceNode" collection
 * @method Doctrine_Collection getResourceSciencecase()    Returns the current record's "ResourceSciencecase" collection
 * @method Resource            setId()                     Sets the current record's "id" value
 * @method Resource            setNodeId()                 Sets the current record's "node_id" value
 * @method Resource            setResourcetypeId()         Sets the current record's "resourcetype_id" value
 * @method Resource            setPersonId()               Sets the current record's "person_id" value
 * @method Resource            setPersonUpdaterId()        Sets the current record's "person_updater_id" value
 * @method Resource            setPersonResponsibleId()    Sets the current record's "person_responsible_id" value
 * @method Resource            setPersonContactId()        Sets the current record's "person_contact_id" value
 * @method Resource            setInstituteId()            Sets the current record's "institute_id" value
 * @method Resource            setResourceRepositoryId()   Sets the current record's "resource_repository_id" value
 * @method Resource            setName()                   Sets the current record's "name" value
 * @method Resource            setUrl()                    Sets the current record's "url" value
 * @method Resource            setIsRestricted()           Sets the current record's "is_restricted" value
 * @method Resource            setAccessComment()          Sets the current record's "access_comment" value
 * @method Resource            setBrief()                  Sets the current record's "brief" value
 * @method Resource            setDescription()            Sets the current record's "description" value
 * @method Resource            setNonEpnLocation()         Sets the current record's "non_epn_location" value
 * @method Resource            setHowto()                  Sets the current record's "howto" value
 * @method Resource            setHowtoUrl1()              Sets the current record's "howto_url1" value
 * @method Resource            setHowtoUrl2()              Sets the current record's "howto_url2" value
 * @method Resource            setHowtoUrl3()              Sets the current record's "howto_url3" value
 * @method Resource            setBiblioRef1()             Sets the current record's "biblio_ref1" value
 * @method Resource            setBiblioRef2()             Sets the current record's "biblio_ref2" value
 * @method Resource            setAssociatedUrl1()         Sets the current record's "associated_url1" value
 * @method Resource            setAssociatedUrl2()         Sets the current record's "associated_url2" value
 * @method Resource            setAssociatedUrl3()         Sets the current record's "associated_url3" value
 * @method Resource            setAssociatedUrl4()         Sets the current record's "associated_url4" value
 * @method Resource            setStartDate()              Sets the current record's "start_date" value
 * @method Resource            setStopDate()               Sets the current record's "stop_date" value
 * @method Resource            setIsEnglish()              Sets the current record's "is_english" value
 * @method Resource            setNonEnglishLanguage()     Sets the current record's "non_english_language" value
 * @method Resource            setLanguage()               Sets the current record's "language" value
 * @method Resource            setResponsibleName()        Sets the current record's "responsible_name" value
 * @method Resource            setResponsibleEmail()       Sets the current record's "responsible_email" value
 * @method Resource            setContactName()            Sets the current record's "contact_name" value
 * @method Resource            setContactEmail()           Sets the current record's "contact_email" value
 * @method Resource            setResourceformatId()       Sets the current record's "resourceformat_id" value
 * @method Resource            setSize()                   Sets the current record's "size" value
 * @method Resource            setProcessLevel()           Sets the current record's "process_level" value
 * @method Resource            setStatus()                 Sets the current record's "status" value
 * @method Resource            setFormatComment()          Sets the current record's "format_comment" value
 * @method Resource            setIsCopy()                 Sets the current record's "is_copy" value
 * @method Resource            setAssociatedUrlComment()   Sets the current record's "associated_url_comment" value
 * @method Resource            setOtherNodeThematic()      Sets the current record's "other_node_thematic" value
 * @method Resource            setInstitute()              Sets the current record's "Institute" value
 * @method Resource            setNode()                   Sets the current record's "Node" value
 * @method Resource            setPerson()                 Sets the current record's "Person" value
 * @method Resource            setPerson4()                Sets the current record's "Person_4" value
 * @method Resource            setPerson5()                Sets the current record's "Person_5" value
 * @method Resource            setPerson6()                Sets the current record's "Person_6" value
 * @method Resource            setNode7()                  Sets the current record's "Node_7" value
 * @method Resource            setResourceformat()         Sets the current record's "Resourceformat" value
 * @method Resource            setResourcetype()           Sets the current record's "Resourcetype" value
 * @method Resource            setResourceExpertise()      Sets the current record's "ResourceExpertise" collection
 * @method Resource            setResourceKeyword()        Sets the current record's "ResourceKeyword" collection
 * @method Resource            setResourceNode()           Sets the current record's "ResourceNode" collection
 * @method Resource            setResourceSciencecase()    Sets the current record's "ResourceSciencecase" collection
 * 
 * @package    gwis
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseResource extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('resource');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('node_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('resourcetype_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('person_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('person_updater_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('person_responsible_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('person_contact_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('institute_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('resource_repository_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 80, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 80,
             ));
        $this->hasColumn('url', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'http://',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('is_restricted', 'boolean', null, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('access_comment', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('brief', 'string', 140, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 140,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('non_epn_location', 'string', 130, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 130,
             ));
        $this->hasColumn('howto', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('howto_url1', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('howto_url2', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('howto_url3', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('biblio_ref1', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('biblio_ref2', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('associated_url1', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('associated_url2', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('associated_url3', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('associated_url4', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('start_date', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('stop_date', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('is_english', 'boolean', null, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('non_english_language', 'enum', 8, array(
             'type' => 'enum',
             'fixed' => 0,
             'unsigned' => false,
             'values' => 
             array(
              0 => 'Chinese',
              1 => 'Danish',
              2 => 'Dutch',
              3 => 'Finnish',
              4 => 'French',
              5 => 'German',
              6 => 'Italian',
              7 => 'Japanese',
              8 => 'Spanish',
              9 => 'Russian',
              10 => 'Other',
             ),
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('language', 'enum', 7, array(
             'type' => 'enum',
             'fixed' => 0,
             'unsigned' => false,
             'values' => 
             array(
              0 => 'English',
              1 => 'French',
              2 => 'German',
              3 => 'Italian',
              4 => 'Spanish',
             ),
             'primary' => false,
             'default' => 'English',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 7,
             ));
        $this->hasColumn('responsible_name', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('responsible_email', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('contact_name', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('contact_email', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('resourceformat_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('size', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('process_level', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('status', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('format_comment', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('is_copy', 'boolean', null, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('associated_url_comment', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('other_node_thematic', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Institute', array(
             'local' => 'institute_id',
             'foreign' => 'id'));

        $this->hasOne('Node', array(
             'local' => 'node_id',
             'foreign' => 'id'));

        $this->hasOne('Person', array(
             'local' => 'person_id',
             'foreign' => 'id'));

        $this->hasOne('Person as Person_4', array(
             'local' => 'person_contact_id',
             'foreign' => 'id'));

        $this->hasOne('Person as Person_5', array(
             'local' => 'person_responsible_id',
             'foreign' => 'id'));

        $this->hasOne('Person as Person_6', array(
             'local' => 'person_updater_id',
             'foreign' => 'id'));

        $this->hasOne('Node as Node_7', array(
             'local' => 'node_id',
             'foreign' => 'id'));

        $this->hasOne('Resourceformat', array(
             'local' => 'resourceformat_id',
             'foreign' => 'id'));

        $this->hasOne('Resourcetype', array(
             'local' => 'resourcetype_id',
             'foreign' => 'id'));

        $this->hasMany('ResourceExpertise', array(
             'local' => 'id',
             'foreign' => 'resource_id'));

        $this->hasMany('ResourceKeyword', array(
             'local' => 'id',
             'foreign' => 'resource_id'));

        $this->hasMany('ResourceNode', array(
             'local' => 'id',
             'foreign' => 'resource_id'));

        $this->hasMany('ResourceSciencecase', array(
             'local' => 'id',
             'foreign' => 'resource_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}