<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Resourceformat', 'doctrine');

/**
 * BaseResourceformat
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $Resource
 * 
 * @method integer             getId()       Returns the current record's "id" value
 * @method string              getName()     Returns the current record's "name" value
 * @method Doctrine_Collection getResource() Returns the current record's "Resource" collection
 * @method Resourceformat      setId()       Sets the current record's "id" value
 * @method Resourceformat      setName()     Sets the current record's "name" value
 * @method Resourceformat      setResource() Sets the current record's "Resource" collection
 * 
 * @package    gwis
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseResourceformat extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('resourceformat');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 30,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Resource', array(
             'local' => 'id',
             'foreign' => 'resourceformat_id'));
    }
}