<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PersonN2dwg', 'doctrine');

/**
 * BasePersonN2dwg
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $person_id
 * @property integer $n2dwg_id
 * @property enum $special_status
 * @property Person $Person
 * @property N2dwg $N2dwg
 * 
 * @method integer     getPersonId()       Returns the current record's "person_id" value
 * @method integer     getN2dwgId()        Returns the current record's "n2dwg_id" value
 * @method enum        getSpecialStatus()  Returns the current record's "special_status" value
 * @method Person      getPerson()         Returns the current record's "Person" value
 * @method N2dwg       getN2dwg()          Returns the current record's "N2dwg" value
 * @method PersonN2dwg setPersonId()       Sets the current record's "person_id" value
 * @method PersonN2dwg setN2dwgId()        Sets the current record's "n2dwg_id" value
 * @method PersonN2dwg setSpecialStatus()  Sets the current record's "special_status" value
 * @method PersonN2dwg setPerson()         Sets the current record's "Person" value
 * @method PersonN2dwg setN2dwg()          Sets the current record's "N2dwg" value
 * 
 * @package    gwis
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePersonN2dwg extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('person_n2dwg');
        $this->hasColumn('person_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('n2dwg_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('special_status', 'enum', 9, array(
             'type' => 'enum',
             'fixed' => 0,
             'unsigned' => false,
             'values' => 
             array(
              0 => 'Leader',
              1 => 'Co-Leader',
             ),
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 9,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Person', array(
             'local' => 'person_id',
             'foreign' => 'id'));

        $this->hasOne('N2dwg', array(
             'local' => 'n2dwg_id',
             'foreign' => 'id'));
    }
}