<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('NodePdsnode', 'doctrine');

/**
 * BaseNodePdsnode
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $node_id
 * @property integer $pdsnode_id
 * @property Node $Node
 * @property Pdsnode $Pdsnode
 * 
 * @method integer     getNodeId()     Returns the current record's "node_id" value
 * @method integer     getPdsnodeId()  Returns the current record's "pdsnode_id" value
 * @method Node        getNode()       Returns the current record's "Node" value
 * @method Pdsnode     getPdsnode()    Returns the current record's "Pdsnode" value
 * @method NodePdsnode setNodeId()     Sets the current record's "node_id" value
 * @method NodePdsnode setPdsnodeId()  Sets the current record's "pdsnode_id" value
 * @method NodePdsnode setNode()       Sets the current record's "Node" value
 * @method NodePdsnode setPdsnode()    Sets the current record's "Pdsnode" value
 * 
 * @package    gwis
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNodePdsnode extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('node_pdsnode');
        $this->hasColumn('node_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('pdsnode_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Node', array(
             'local' => 'node_id',
             'foreign' => 'id'));

        $this->hasOne('Pdsnode', array(
             'local' => 'pdsnode_id',
             'foreign' => 'id'));
    }
}