<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('NodeSciencecase', 'doctrine');

/**
 * BaseNodeSciencecase
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $node_id
 * @property integer $sciencecase_id
 * @property Node $Node
 * @property Sciencecase $Sciencecase
 * 
 * @method integer         getNodeId()         Returns the current record's "node_id" value
 * @method integer         getSciencecaseId()  Returns the current record's "sciencecase_id" value
 * @method Node            getNode()           Returns the current record's "Node" value
 * @method Sciencecase     getSciencecase()    Returns the current record's "Sciencecase" value
 * @method NodeSciencecase setNodeId()         Sets the current record's "node_id" value
 * @method NodeSciencecase setSciencecaseId()  Sets the current record's "sciencecase_id" value
 * @method NodeSciencecase setNode()           Sets the current record's "Node" value
 * @method NodeSciencecase setSciencecase()    Sets the current record's "Sciencecase" value
 * 
 * @package    gwis
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNodeSciencecase extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('node_sciencecase');
        $this->hasColumn('node_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('sciencecase_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Node', array(
             'local' => 'node_id',
             'foreign' => 'id'));

        $this->hasOne('Sciencecase', array(
             'local' => 'sciencecase_id',
             'foreign' => 'id'));
    }
}