<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('N2dwgSciencecase', 'doctrine');

/**
 * BaseN2dwgSciencecase
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $n2dwg_id
 * @property integer $sciencecase_id
 * @property N2dwg $N2dwg
 * @property Sciencecase $Sciencecase
 * 
 * @method integer          getN2dwgId()        Returns the current record's "n2dwg_id" value
 * @method integer          getSciencecaseId()  Returns the current record's "sciencecase_id" value
 * @method N2dwg            getN2dwg()          Returns the current record's "N2dwg" value
 * @method Sciencecase      getSciencecase()    Returns the current record's "Sciencecase" value
 * @method N2dwgSciencecase setN2dwgId()        Sets the current record's "n2dwg_id" value
 * @method N2dwgSciencecase setSciencecaseId()  Sets the current record's "sciencecase_id" value
 * @method N2dwgSciencecase setN2dwg()          Sets the current record's "N2dwg" value
 * @method N2dwgSciencecase setSciencecase()    Sets the current record's "Sciencecase" value
 * 
 * @package    gwis
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseN2dwgSciencecase extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('n2dwg_sciencecase');
        $this->hasColumn('n2dwg_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('sciencecase_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('N2dwg', array(
             'local' => 'n2dwg_id',
             'foreign' => 'id'));

        $this->hasOne('Sciencecase', array(
             'local' => 'sciencecase_id',
             'foreign' => 'id'));
    }
}