<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Domain', 'doctrine');

/**
 * BaseDomain
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $Person
 * @property Doctrine_Collection $PersonDomain
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getName()         Returns the current record's "name" value
 * @method Doctrine_Collection getPerson()       Returns the current record's "Person" collection
 * @method Doctrine_Collection getPersonDomain() Returns the current record's "PersonDomain" collection
 * @method Domain              setId()           Sets the current record's "id" value
 * @method Domain              setName()         Sets the current record's "name" value
 * @method Domain              setPerson()       Sets the current record's "Person" collection
 * @method Domain              setPersonDomain() Sets the current record's "PersonDomain" collection
 * 
 * @package    gwis
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDomain extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('domain');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Person', array(
             'local' => 'id',
             'foreign' => 'domain_id'));

        $this->hasMany('PersonDomain', array(
             'local' => 'id',
             'foreign' => 'domain_id'));
    }
}