<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('InstituteActivity', 'doctrine');

/**
 * BaseInstituteActivity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $activity_id
 * @property integer $institute_id
 * @property enum $special_status
 * @property Activity $Activity
 * @property Institute $Institute
 * 
 * @method integer           getActivityId()     Returns the current record's "activity_id" value
 * @method integer           getInstituteId()    Returns the current record's "institute_id" value
 * @method enum              getSpecialStatus()  Returns the current record's "special_status" value
 * @method Activity          getActivity()       Returns the current record's "Activity" value
 * @method Institute         getInstitute()      Returns the current record's "Institute" value
 * @method InstituteActivity setActivityId()     Sets the current record's "activity_id" value
 * @method InstituteActivity setInstituteId()    Sets the current record's "institute_id" value
 * @method InstituteActivity setSpecialStatus()  Sets the current record's "special_status" value
 * @method InstituteActivity setActivity()       Sets the current record's "Activity" value
 * @method InstituteActivity setInstitute()      Sets the current record's "Institute" value
 * 
 * @package    gwis
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInstituteActivity extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('institute_activity');
        $this->hasColumn('activity_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('institute_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('special_status', 'enum', 11, array(
             'type' => 'enum',
             'fixed' => 0,
             'unsigned' => false,
             'values' => 
             array(
              0 => 'Coordinator',
             ),
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 11,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Activity', array(
             'local' => 'activity_id',
             'foreign' => 'id'));

        $this->hasOne('Institute', array(
             'local' => 'institute_id',
             'foreign' => 'id'));
    }
}