<?php

/**
 * ActivityitemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActivityitemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActivityitemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Activityitem');
    }
}