<?php

/**
 * ActivitytypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActivitytypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActivitytypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Activitytype');
    }
}