<?php

/**
 * DocDoctypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DocDoctypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DocDoctypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DocDoctype');
    }
}