<?php

/**
 * DocTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DocTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DocTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Doc');
    }
}