<?php

/**
 * EventPersonTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventPersonTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EventPersonTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EventPerson');
    }
}