<?php

/**
 * InstituteActivityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InstituteActivityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InstituteActivityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InstituteActivity');
    }
}