<?php

/**
 * InstituteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InstituteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InstituteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Institute');
    }
}