<?php

/**
 * InstituteKeywordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InstituteKeywordTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InstituteKeywordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InstituteKeyword');
    }
}