<?php

/**
 * KeywordtypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class KeywordtypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object KeywordtypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Keywordtype');
    }
}