<?php

/**
 * N2dwgTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class N2dwgTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object N2dwgTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('N2dwg');
    }
}