<?php

/**
 * N2dwgSciencecaseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class N2dwgSciencecaseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object N2dwgSciencecaseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('N2dwgSciencecase');
    }
}