<?php

/**
 * NodeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NodeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NodeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Node');
    }
}