<?php

/**
 * NodePdsnodeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NodePdsnodeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NodePdsnodeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NodePdsnode');
    }
}