<?php

/**
 * PdsnodeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PdsnodeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PdsnodeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Pdsnode');
    }
}