<?php

/**
 * PersonActivityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PersonActivityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PersonActivityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PersonActivity');
    }
}