<?php

/**
 * PersonExpertiseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PersonExpertiseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PersonExpertiseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PersonExpertise');
    }
}