<?php

/**
 * PersonN2dwgTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PersonN2dwgTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PersonN2dwgTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PersonN2dwg');
    }
}