<?php

/**
 * PersonKeywordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PersonKeywordTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PersonKeywordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PersonKeyword');
    }
}