<?php

/**
 * PersonDomainTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PersonDomainTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PersonDomainTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PersonDomain');
    }
}