<?php

/**
 * ResourceSciencecaseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ResourceSciencecaseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ResourceSciencecaseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ResourceSciencecase');
    }
}