<?php

/**
 * ResourceExpertiseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ResourceExpertiseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ResourceExpertiseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ResourceExpertise');
    }
}