<?php

/**
 * ResourceNodeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ResourceNodeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ResourceNodeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ResourceNode');
    }
}