<?php

/**
 * ResourcetypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ResourcetypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ResourcetypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Resourcetype');
    }
}