<?php

/**
 * ResourceKeywordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ResourceKeywordTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ResourceKeywordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ResourceKeyword');
    }
}