<?php

/**
 * SciencecaseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SciencecaseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SciencecaseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Sciencecase');
    }
}